[project]
name = "hardware-monorepo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cocotb>=1.9.2",
    "cocotb-bus>=0.2.1",
    "pyshark>=0.6",
    "pytest>=8.4.2",
]
